-- SEED DATA: KLANTEN (375 customers)

INSERT OR IGNORE INTO klanten (naam, type, contactpersoon, email, telefoonnummer, adres, postcode, plaats, land, kvk_nummer, btw_nummer, iban, marge_max) VALUES
    ('M.C. Claassen', 'bureau', NULL, 'mcc.2006@hotmail.com', NULL, 'Camino Viejo de Valencia 8 1e izq', NULL, NULL, 'Nederland', NULL, NULL, 'NL05 RABO 0383 7113 04', NULL),
    ('Bright Home Rentals B.V.', 'bureau', NULL, 'administratie@brighthomerentals.nl', NULL, 'Ebweg 73', NULL, 'BARENDRECHT', 'Nederland', '66838452.0', NULL, 'NL62 RABO 0312 8075 46', NULL),
    ('T.A. van der Burg', 'bureau', NULL, 'vanderburgron@gmail.com', NULL, 'Heeswijk 113', NULL, 'Montfoort', 'Nederland', '53093623.0', NULL, 'NL67 INGB 0795 2367 27', NULL),
    ('Randstad Wonen', 'bureau', NULL, 'info@randstadwonen.nl', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('Ruva Vastgoed B.V.', 'zakelijk', NULL, 'beheer@ruvavastgoed.nl', NULL, 'Burgemeester van Campenhoutstraat 2', NULL, 'MADE', 'Nederland', '52768384.0', NULL, 'NL93 RABO 0116 6871 50', NULL),
    ('GOTI Verhuur B.V.', 'zakelijk', NULL, 'info@gotiverhuur.nl', NULL, 'Noorderhaven 63', NULL, 'Harlingen', 'Nederland', '1098148.0', NULL, 'NL94 INGB 0665 1314 02', NULL),
    ('Maatschap J.W. Meershoek & W.M. Meershoek', 'zakelijk', NULL, 'j.meershoek1@chello.nl', NULL, 'Grootzand 11', NULL, 'HOEK VAN HOLLAND', 'Nederland', NULL, NULL, 'NL37 ABNA 0406 1514 07', NULL),
    ('Joost de Jong Holding B.V.', 'particulier', NULL, 'jcdejong@aol.nl', NULL, 'Wetterkrite 49', NULL, 'Goutum', 'Nederland', '63936070.0', NULL, 'NL70 INGB 0007 1264 17', NULL),
    ('H.C. van Os - Remeeus', 'particulier', NULL, 'marcel@cohousingnederland.nl', NULL, 'Iependaal 19', NULL, 'ROZENBURG', 'Nederland', NULL, NULL, 'NL60 RABO 0369 8896 57', NULL),
    ('Klaas Bos', 'particulier', NULL, 'klaas.bos@example.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('Finest Housing B.V.', 'particulier', NULL, 'backoffice@finesthousing.nl', NULL, 'John F. Kennedylaan 246', NULL, 'PANNINGEN', 'Nederland', '75080060.0', NULL, 'NL57 RABO 0342 8897 61', NULL),
    ('M.J. van Os', 'particulier', NULL, 'marcelvanos0@gmail.com', NULL, 'Burg Letteweg 31', NULL, 'OOSTVOORNE', 'Nederland', NULL, NULL, 'NL21 INGB 0664 8003 94', NULL),
    ('United Homes B.V.', 'particulier', NULL, 'administratie@unitedhomes.eu', NULL, 'Van Vollenhovenstraat 10', NULL, 'Rotterdam', 'Nederland', NULL, NULL, 'NL85 RABO 0131 3612 60', NULL),
    ('Edy Comert BV', 'particulier', NULL, 'office@edycom.ro', NULL, 'Bergerweg 61', NULL, 'Sittard', 'Nederland', '51124769.0', NULL, NULL, NULL),
    ('Flexcraft SSC BV', 'particulier', NULL, 'huisvesting@flexcraft.eu', NULL, 'Einsteinstraat 9 B', NULL, 'Gorinchem', 'Nederland', '67541690.0', NULL, NULL, NULL),
    ('Vaktec BV', 'particulier', NULL, 'j.deboer@vaktec.nl', NULL, 'Kielerbocht 29A', NULL, 'Groningen', 'Nederland', NULL, NULL, NULL, NULL),
    ('Tradiro Services B.V.', 'particulier', NULL, 'facturen@tradiro.nl', NULL, 'Honderdland 960', NULL, 'Maasdijk', 'Nederland', '59979135.0', NULL, 'NL05 RABO 0154 0739 89', NULL),
    ('Sagius Uitzenders B.V.', 'particulier', NULL, 'facturen@sagiusuitzenders.nl', NULL, 'Bleiswijkseweg 43', NULL, 'ZOETERMEER', 'Nederland', NULL, NULL, 'NL41 RABO 0145 8741 25', NULL),
    ('Groene Hart Service Detachering B.V.', 'bureau', NULL, 'facturatie@groenehartservice.nl', NULL, 'Fokkerstraat 5', NULL, 'REEUWIJK', 'Nederland', NULL, NULL, 'NL41 INGB 0650 5389 00', NULL),
    ('S. Dolstra', 'particulier', NULL, 'dolstra@yahoo.com', NULL, 'Molenweg 10 a', NULL, 'KRUISLAND', 'Nederland', NULL, NULL, 'NL51 RABO 0194 3333 02', NULL),
    ('The Housing Guild B.V.', 'particulier', NULL, 'r.nijboer@degildegroep.nl', NULL, 'Blankenstein 136', NULL, 'MEPPEL', 'Nederland', NULL, NULL, 'NL81 ABNA 0823 0941 54', NULL),
    ('J. Hermans', 'particulier', NULL, 'frankjolanda@online.nl', NULL, 'Meedhuizerweg 5', NULL, 'MEEDHUIZEN', 'Nederland', NULL, NULL, 'NL92 RABO 0154 3249 14', NULL),
    ('S. Bakker OPH Verhuur', 'particulier', NULL, NULL, NULL, 'Hoofdweg 7', NULL, 'Hitzum', 'Nederland', NULL, NULL, 'NL85 INGB 0102 8401 21', NULL),
    ('V.O.F. Groepsaccommodaties Drenthe', 'particulier', NULL, NULL, NULL, 'Westeind 12', NULL, 'Norg', 'Nederland', '67963692.0', NULL, NULL, NULL),
    ('O.J.P Soc Construções', 'particulier', NULL, 'romeu.ferreira@ojp.pt', NULL, 'Rua Quinta da Tapada 20 R C', NULL, NULL, 'Portugal', NULL, NULL, 'PT50 0010 0000 5582 3720 0019 1', NULL),
    ('Vivir Wonen', 'particulier', NULL, 'info@vivirwonen.nl', NULL, 'Postbus 811', NULL, 'Gorinchem', 'Nederland', '58693807.0', NULL, 'NL52 RABO 0106 0699 77', NULL),
    ('Global Accomodation Solutions (Incassobureau)', 'particulier', NULL, 'info@globalaccommodation.solutions', NULL, 'Jan Pietersz. Coenstraat 7', NULL, '''S-GRAVENHAGE', 'Nederland', '78155797.0', NULL, 'NL76 INGB 0008 9801 73', NULL),
    ('Alis Vastgoed B.V.', 'particulier', NULL, 'rifat@prokonak.nl', NULL, 'Fruitweg 25', NULL, '''S-GRAVENHAGE', 'Nederland', NULL, NULL, NULL, NULL),
    ('Resource One B.V.', 'particulier', NULL, 'info@qualityhomerentals.nl', NULL, 'Nobelstraat 76', NULL, 'BRIELLE', 'Nederland', '74887068.0', NULL, 'NL95 KNAB 0259 2344 78', NULL),
    ('Team Home Rentals B.V.', 'particulier', NULL, 'administratie@teamhomerentals.nl', NULL, 'Dopplerweg1', NULL, 'Spijkenisse', 'Nederland', '71523561.0', NULL, 'NL61 RABO 0330 2631 02', NULL),
    ('Direct Rendement B.V.', 'particulier', NULL, 'info@directrendement.nl', NULL, 'Kortedijk 57', NULL, 'VLAARDINGEN', 'Nederland', '72724382.0', NULL, 'NL09 INGB 0008 5322 69', NULL),
    ('Interim Jobs B.V.', 'particulier', NULL, 'e.ozel@interimjobs.nl', NULL, 'Vlierwerf 3 d', NULL, 'ROOSENDAAL', 'Nederland', '67044360.0', NULL, 'NL83 RABO 0313 5561 05', NULL),
    ('L.M. Schilstra', 'particulier', NULL, NULL, NULL, 'Adres onbekend', NULL, NULL, 'Nederland', NULL, NULL, 'NL17 RABO 0158 8674 16', NULL),
    ('Employ', 'particulier', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('Best@Work B.V.', 'particulier', NULL, 'info@bestatwork.nl', NULL, 'Industrieweg 74-76', NULL, 'WAALWIJK', 'Nederland', '74210025.0', NULL, NULL, NULL),
    ('WS Detachering BV', 'particulier', NULL, 'administratie@workstead.nl', NULL, 'Barneveldsestraat 44', NULL, 'Renswoude', 'Nederland', NULL, NULL, NULL, NULL),
    ('Flowerhill B.V.', 'bureau', NULL, 'jb.heuvel@quicknet.nl', NULL, 'Prinses Marijkestraat 36', NULL, 'Andijk', 'Nederland', '69891478.0', NULL, NULL, NULL),
    ('J.D. Jongsma', 'particulier', NULL, 'jand.jongsma@icloud.com', NULL, 'Tamboerstraat 16', NULL, 'LOON OP ZAND', 'Nederland', NULL, NULL, 'NL88 INGB 0794 4823 68', NULL),
    ('Multiserwis SP z o.o.', 'particulier', NULL, 'karol.pastucha@bilfinger.com', NULL, 'ul. Prudnicka 40', NULL, 'Krapkowise', 'Polen', '120630.0', NULL, 'DE81 7007 0010 0206 0184 00', NULL),
    ('A.W.N. Alkemade', 'particulier', NULL, 'melkveebedrijfalkemade@kpnmail.nl', NULL, 'Laan van Pluymestein 36', NULL, 'WASSENAAR', 'Nederland', NULL, NULL, 'NL80 ABNA 0608 8189 41', NULL),
    ('HBBwonen.nu B.V.', 'particulier', NULL, 'info@hbbwonen.nu', NULL, 'Stationsstraat 13', NULL, 'ROSMALEN', 'Nederland', '70532222.0', NULL, 'NL79 INGB 0006 8359 34', NULL),
    ('S. Meijer', 'particulier', NULL, 'siebmeijer@msn.com', NULL, 'Zevenhuizen 2', NULL, 'FRANEKER', 'Nederland', NULL, NULL, 'NL76 INGB 0679 9560 42', NULL),
    ('De Pagter Vastgoed B.V.', 'particulier', NULL, 'info@depagtervastgoed.nl', NULL, 'Molenwater 2', NULL, 'MIDDELBURG', 'Nederland', '22033473.0', NULL, 'NL91 INGB 0650 5095 79', NULL),
    ('Marco is Vastgoed B.V.', 'particulier', NULL, 'marco@dewitteaap.nl', NULL, 'Lombardkade 29 C', NULL, 'ROTTERDAM', 'Nederland', NULL, NULL, 'NL33 RABO 0349 6595 32', NULL),
    ('Kiose Yacht Finishing', 'particulier', NULL, 'metinkiose@yahoo.co.uk', NULL, 'Kiou 6', NULL, 'Keatsini  Athens', 'Griekenland', NULL, NULL, NULL, NULL),
    ('European Business Brokers', 'particulier', NULL, 'daniel@reppz.com', NULL, 'Dr. Duyvendakhof 32', NULL, 'Oud Beijerland', 'Nederland', NULL, NULL, NULL, NULL),
    ('Global Expatriate Services SL', 'particulier', NULL, 'lodewijk@globexs.com', NULL, 'Calle Del Pintor Salvador Abril 35', NULL, 'Valencia', 'Spanje', NULL, NULL, 'ES59 0049 0621 1228 1065 0833', NULL),
    ('Light Personeelsdiensten', 'particulier', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('Pol Flex B.V.', 'bureau', NULL, 'administratie@polflexbv.nl', NULL, 'Ouddeelstraat 7 a', NULL, 'LEEUWARDEN', 'Nederland', '73251127.0', NULL, 'NL22 SNSB 0267 9799 16', NULL),
    ('I.I. Bhaggoe', 'particulier', NULL, NULL, NULL, 'Jan Campertlaan 8', NULL, 'SPIJKENISSE', 'Nederland', NULL, NULL, 'NL56 INGB 0671 6016 95', NULL),
    ('De Borgmeren B.V.', 'particulier', NULL, 'borgmeren@live.nl', NULL, 'Hoofdweg 34', NULL, 'SCHARMER', 'Nederland', NULL, NULL, 'NL54 RABO 0366 9535 75', NULL),
    ('van Heeswijk', 'particulier', NULL, 'verhuur@reham.nl', NULL, 'Adres onbekend', NULL, NULL, 'Nederland', NULL, NULL, 'NL32 INGB 0007 1086 71', NULL),
    ('Business Housing', 'particulier', NULL, 'eliane@zamens.nl', NULL, 'Oosteinde 26', NULL, 'Oud Alblas', 'Nederland', '69861846.0', NULL, 'NL50 RABO 0323 5939 68', NULL),
    ('Finishing De Luxe GmbH', 'particulier', NULL, 'katja.korotchenko@finishing-deluxe.com', NULL, 'Burgermeister Schade Strasse 20', NULL, 'SCHONKIRCHEN', 'Nederland', NULL, NULL, NULL, NULL),
    ('Zeeland Housing Facility B.V.', 'particulier', NULL, 'info@housingzeeland.nl', NULL, 'Prinsenhove 168', NULL, 'Middelburg', 'Nederland', '75463547.0', NULL, NULL, NULL),
    ('MvB Services', 'particulier', NULL, 'driver@meindertvanbuuren.com', NULL, 'Windgatseweg 2', NULL, 'ROCKANJE', 'Nederland', '70892865.0', NULL, 'NL70 RABO 0327 4853 45', NULL),
    ('Vleesbewerking van der Pijl B.V.', 'particulier', NULL, 'facturen@vleesbewerkingvanderpijl.nl', NULL, 'Cypresbaan 6a', NULL, 'CAPELLE AAN DEN IJSSEL', 'Nederland', '70437769.0', NULL, NULL, NULL),
    ('City Estate B.V.', 'particulier', NULL, 'huren@cityestate.nl', NULL, 'Oudegracht 312', NULL, 'UTRECHT', 'Nederland', '77525027.0', NULL, 'NL95 INGB 0006 7773 49', NULL),
    ('A.Y. Nicolai', 'particulier', NULL, 'famnicolai@hotmail.com', NULL, 'De Setangel 14', NULL, 'GROU', 'Nederland', NULL, NULL, 'NL44 INGB 0006 4538 99', NULL),
    ('M. Poel', 'bureau', NULL, 'monique_pruijsen@hotmail.com', NULL, 'Esdoornlaan 64', NULL, 'ROZENBURG', 'Nederland', NULL, NULL, 'NL96 RABO 0138 5699 08', NULL),
    ('Space4U B.V.', 'particulier', NULL, 'info@space4ubv.nl', NULL, 'Kastelenplein 4', NULL, 'EINDHOVEN', 'Nederland', '77266099.0', NULL, 'NL44 INGB 0007 4063 42', NULL),
    ('S. Marinus (zie 50200)', 'particulier', NULL, NULL, NULL, '''t Deel 29', NULL, 'Drachten', 'Nederland', NULL, NULL, 'NL16 RABO 0348 0756 34', NULL),
    ('J. van Heeswijk', 'particulier', NULL, 'verhuur@reham.nl', NULL, 'Kortrijksesteenweg 1004', NULL, NULL, 'Nederland', NULL, NULL, 'NL32 INGB 0007 1086 71', NULL),
    ('V.B.A. Beheer B.V.', 'particulier', NULL, 'vbabv@outlook.com', NULL, 'Ouddeelstraat 9', NULL, 'Leeuwarden', 'Nederland', '60392525.0', NULL, 'NL72 ABNA 0508 0206 62', NULL),
    ('Quality Home Rentals', 'particulier', NULL, 'info@qualityhomerentals.nl', NULL, 'Vlinderslag 4', NULL, 'OOSTVOORNE', 'Nederland', '76436357.0', NULL, 'NL19 KNAB 0259 8013 56', NULL),
    ('P. Gryspeerdt', 'particulier', NULL, 'verhuur@reham.nl', NULL, 'Klimopstraat 1', NULL, NULL, 'Nederland', NULL, NULL, 'NL32 INGB 0007 1086 71', NULL),
    ('A. Verschueren', 'particulier', NULL, 'verhuur@reham.nl', NULL, 'Mangelbeekstraat 1', NULL, NULL, 'Nederland', NULL, NULL, 'NL32 INGB 0007 1086 71', NULL),
    ('Langweer Vastgoed B.V.', 'particulier', NULL, 'jan@wassenaarvastgoed.nl', NULL, 'Buorren 15', NULL, 'LANGWEER', 'Nederland', NULL, NULL, 'NL64 RABO 0312 3429 77', NULL),
    ('A. Dzaka', 'bureau', NULL, 'adisa-kemo@hotmail.com', NULL, 'Merwedepad 29', NULL, 'Rozenburg ZH', 'Nederland', NULL, NULL, NULL, NULL),
    ('M.A. Pronk', 'particulier', NULL, 'mp64@hotmail.com', NULL, 'Oosteinde 102', NULL, 'BERKHOUT', 'Nederland', NULL, NULL, 'NL31 INGB 0799 7542 77', NULL),
    ('HJC Service', 'particulier', NULL, 'benhanan010@gmail.com', NULL, 'Maarland Zuidzijde 27', NULL, 'Brielle', 'Nederland', '71585737.0', NULL, 'NL78 SNSB 0786 0245 77', NULL),
    ('StayProjects Group Netherlands B.V.', 'particulier', NULL, 'sametkaya@staysolutions.com', NULL, 'Bijdorpplein 9 - 11', NULL, 'BARENDRECHT', 'Nederland', '20160652.0', NULL, 'NL34 RABO 0152 5813 16', NULL),
    ('Vast-PS Housing', 'bureau', NULL, 'info@vast-ps.nl', NULL, 'Verlaatsweg 33', NULL, 'SPIERDIJK', 'Nederland', NULL, NULL, 'NL79 RABO 0335 3714 77', NULL),
    ('Edy Comert SRL', 'particulier', NULL, 'office@edycom.ro', NULL, 'Strada Rapsodiei 47', NULL, 'Constanta', 'Roemenië', NULL, NULL, 'RO73 BACX 0000 0008 7210 3014', NULL),
    ('Fryslân Homes', 'bureau', NULL, 'backoffice@fryslanhomes.frl', NULL, 'Struikheide 6', NULL, 'Heerenveen', 'Nederland', '63969823.0', NULL, 'NL44 INGB 0006 4538 99', NULL),
    ('K-Power Netherlands Kft', 'particulier', NULL, NULL, NULL, 'Wetering Oost 48', NULL, 'Wetering', 'Nederland', NULL, NULL, NULL, NULL),
    ('A.P.W. Koedooder', 'particulier', NULL, 'apwkoedooder@gmail.com', NULL, 'Isaac Beeckmanhof 1', NULL, 'ROTTERDAM', 'Nederland', NULL, NULL, 'NL21 INGB 0006 8135 04', NULL),
    ('Gridin''s Group LT', 'particulier', NULL, 'a.kozlova@gridins.com', NULL, 'Tomo g. 20-2', NULL, 'Klaipeda', 'Litouwen', NULL, NULL, NULL, NULL),
    ('L. Keizer', 'zakelijk', NULL, 'leendertkeizer@hotmail.com', NULL, 'Rettichlaan 8', NULL, '''S-GRAVENZANDE', 'Nederland', NULL, NULL, 'NL16 INGB 0675 4147 09', NULL),
    ('Flex House Renting B.V.', 'zakelijk', NULL, 'e.ozel@interimjobs.nl', NULL, 'Vlierwerf 3 d', NULL, 'ROOSENDAAL', 'Nederland', '78002222.0', NULL, 'NL35 INGB 0008 0442 79', NULL),
    ('T.A. Middelkoop', 'zakelijk', NULL, 'tunny.10@hotmail.com', NULL, 'Vlietskade 9015', NULL, 'ARKEL', 'Nederland', NULL, NULL, 'NL70 RABO 0397 2182 57', NULL),
    ('Crown Uitzendgroep', 'zakelijk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('UAB Toromega', 'zakelijk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('Orange Investments Group', 'zakelijk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('4 Homes B.V.', 'zakelijk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('Eastmen', 'zakelijk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('Industrial Technical Services Srl', 'zakelijk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('Housing en Transport Facilities BV', 'zakelijk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('Stay21', 'zakelijk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
    ('Marseille Bax Van Maanen Rotterdamse account.', 'particulier', NULL, NULL, NULL, 'Molenweg 11-13', NULL, 'Rozenburg', 'Nederland', '24220887.0', NULL, 'NL39 ABNA 0800 7349 55', NULL),
    ('Autobedrijf W. Bronder', 'particulier', NULL, 'k.bronder@outlook.com', NULL, 'Boomweg 17', NULL, 'Rockanje', 'Nederland', '24234431.0', NULL, 'NL22 RABO 0350 2406 63', NULL),
    ('DNACC B.V. / Rolbakkie', 'particulier', NULL, NULL, NULL, 'Aziehavenweg 18', NULL, 'Amsterdam', 'Nederland', '37155744.0', NULL, 'NL94 INGB 0007 2004 81', NULL),
    ('Dynalinx B.V.', 'particulier', NULL, NULL, NULL, 'Pascalweg 15', NULL, 'Hellevoetsluis', 'Nederland', '6092423.0', NULL, 'NL70 RABO 0351 6436 80', NULL),
    ('Furniture Lease', 'particulier', NULL, NULL, NULL, 'Sint Walburg 20 b', NULL, 'Zetten', 'Nederland', '73701297.0', NULL, 'NL67 RABO 0133 9564 31', NULL),
    ('Hiltermann Lease B.V.', 'particulier', NULL, NULL, NULL, 'Diamantlaan 6', NULL, 'Hoofddorp', 'Nederland', '34216188.0', NULL, 'NL32 ABNA 0633 0060 76', NULL),
    ('Kadaster', 'particulier', NULL, NULL, NULL, 'George Hintzenweg 77', NULL, 'Rotterdam', 'Nederland', '8215619.0', NULL, 'NL42 INGB 0006 3919 52', NULL),
    ('Keypro B.V.', 'particulier', NULL, NULL, NULL, 'Suikerlaan 15', NULL, 'Groningen', 'Nederland', '52688844.0', NULL, 'NL76 INGB 0007 4343 81', NULL),
    ('Lago Personeelshuisvesting B.V.', 'particulier', NULL, 'facturen@lagopersoneelshuisvesting.nl', NULL, 'Kwinkweerd 100A', NULL, 'Lochem', 'Nederland', '67649815.0', NULL, NULL, NULL),
    ('TOTAL Nederland N.V.', 'particulier', NULL, NULL, NULL, 'Bezuidenhoutseweg 273', NULL, '''s-Gravenhage', 'Nederland', '24106171.0', NULL, 'NL83 DEUT 0265 2210 48', NULL),
    ('Van der Wal Bedrijfshuisvesting B.V.', 'particulier', NULL, NULL, NULL, 'Beeldsweg 6 a', NULL, NULL, 'Nederland', '24243929.0', NULL, 'NL46 RABO 0166 3751 79', NULL),
    ('YaY', 'particulier', NULL, 'yolanda@youronlineassociate.nl', NULL, 'Kikkerveen 217', NULL, 'Spijkenisse', 'Nederland', '74545191.0', NULL, 'NL33 KNAB 0259 4355 11', NULL),
    ('LZ Auto- en Motorservice B.V.', 'particulier', NULL, 'lz@lzautoservice.nl', NULL, 'Dwarsweg 32', NULL, 'Rozenburg', 'Nederland', '64117367.0', NULL, NULL, NULL),
    ('Verkeersschool Nobel', 'particulier', NULL, 'info@verkeersschoolnobel.nl', NULL, 'Oostdijk 37', NULL, 'Hellevoetsluis', 'Nederland', NULL, NULL, NULL, NULL),
    ('OGSS BV', 'particulier', NULL, 'administratie@ooijkaas.nl', NULL, 'Hoofdstraat 127A', NULL, 'Schiedam', 'Nederland', NULL, NULL, NULL, NULL),
    ('Bator V.O.F.', 'particulier', NULL, NULL, NULL, 'Jacob Marisstraat 37', NULL, 'Zwijndrecht', 'Nederland', '53286634.0', NULL, 'NL19 INGB 0006 0624 69', NULL),
    ('Homekeur B.V.', 'particulier', NULL, NULL, NULL, 'Gieterijstraat 82', NULL, 'Ridderkerk', 'Nederland', '67431496.0', NULL, 'NL71 INGB 0007 6493 26', NULL),
    ('Reham Verhuur B.V.', 'particulier', NULL, NULL, NULL, 'Terneuzensestraat 10', NULL, 'Zaamslag', 'Nederland', '74947087.0', NULL, 'NL32 INGB 0007 1086 71', NULL),
    ('Verhuur en onderhoudsbedrijf Hilaard', 'particulier', NULL, 'verhuurenonderhoudsbedrijfhilaard@outlook.com', NULL, 'Hilaerdermieden 1', NULL, 'HILAARD', 'Nederland', '77467442.0', NULL, 'NL56 INGB 0009 0228 25', NULL),
    ('Oxrooms', 'particulier', NULL, 'info@ox-rooms.nl', NULL, 'Antwerpsestraat 62', NULL, 'PUTTE', 'Nederland', '77559355.0', NULL, 'NL02 INGB 0008 3414 02', NULL),
    ('Vaktec B.V.', 'particulier', NULL, 'inkoopfacturen@vaktec.nl', NULL, 'Kieler Bocht 29 a', NULL, 'GRONINGEN', 'Nederland', '1134291.0', NULL, 'NL93 ABNA 0244 7895 41', NULL),
    ('Hugo Vastgoed B.V.', 'particulier', NULL, 'administratie@hemobeheer.nl', NULL, 'Academiesingel 37 A', NULL, 'BREDA', 'Nederland', '81215169.0', NULL, 'NL06 ABNA 0889 9369 43', NULL),
    ('Plural Albufeira S.R.L.', 'particulier', NULL, 'office@plural.ro', NULL, 'Strada SLT. POPA, NR 7, Bloc 17, Scara 2, Etaj 4, Ap. 38', NULL, 'Bucuresti Sectorul 5', 'Roemenië', NULL, NULL, NULL, NULL),
    ('ERGO Construction doo', 'particulier', NULL, 'ergo.const@gmail.com', NULL, 'Frana Supila 6', NULL, 'Rijeka', 'Kroatië', NULL, NULL, NULL, NULL),
    ('Flex Pons B.V.', 'particulier', NULL, 'f.tuncer@flexpons.nl', NULL, 'Boschstraat 43', NULL, 'BREDA', 'Nederland', '60580364.0', NULL, 'NL31 INGB 0006 2037 76', NULL),
    ('A. Ghali', 'particulier', NULL, NULL, NULL, 'Rooseveltlaan 956', NULL, 'Utrecht', 'Nederland', NULL, NULL, 'NL11 ABNA 0560 7581 38', NULL),
    ('DB Beheer B.V.', 'particulier', NULL, 'info@dbwork.com', NULL, 'Sportlaan 257', NULL, 'SLIEDRECHT', 'Nederland', '62123440.0', NULL, NULL, NULL),
    ('United Homes Inhouse B.V.', 'particulier', NULL, 'administratie@unitedhomes.eu', NULL, 'Van Vollenhovenstraat 10', NULL, 'Rotterdam', 'Nederland', '82140030.0', NULL, 'NL65 RABO 0367 7098 80', NULL),
    ('A. Blaszcak', 'particulier', NULL, 'info@aneta.nl', NULL, 'Prof. Kernkampstraat 24', NULL, 'Tilburg', 'Nederland', NULL, NULL, 'NL22 ABNA 0425 7631 37', NULL),
    ('Level 5 Assetmanagement B.V.', 'particulier', NULL, NULL, NULL, 'Edisonweg 12', NULL, 'ALBLASSERDAM', 'Nederland', '80486142.0', NULL, 'NL78 INGB 0006 3405 73', NULL),
    ('Stichting Bewaring PRMD', 'particulier', NULL, 'finance1@prmd.nl', NULL, 'Kranenburgweg 131', NULL, '''S-GRAVENHAGE', 'Nederland', '64066703.0', NULL, 'NL78 INGB 0006 3405 73', NULL),
    ('CB-Homes B.V.', 'particulier', NULL, 'info@cb-homes.nl', NULL, 'Langeweg 3 a', NULL, 'OOSTVOORNE', 'Nederland', '78756081.0', NULL, 'NL61 INGB 0006 7055 02', NULL),
    ('Interwel Oost B.V.', 'particulier', NULL, 'facturen@interwel.nl', NULL, 'Rollecate 71', NULL, 'NIEUWLEUSEN', 'Nederland', '4067303.0', NULL, 'NL13 ABNA 0627 7737 53', NULL),
    ('OJP B.V.', 'particulier', NULL, 'rita.guimaraes@ojp.pt', NULL, 'Marten Meesweg 25G', NULL, 'Rotterdam', 'Nederland', '84474432.0', NULL, 'NL10 INGB 0674 8358 24', NULL),
    ('AmDor Projecten B.V.', 'particulier', NULL, 'invoice@amdorprojecten.nl', NULL, 'Maarsseveensevaart 92', NULL, 'MAARSSEN', 'Nederland', '72342315.0', NULL, 'NL51 INGB 0009 3373 89', NULL),
    ('Vondellaan Vastgoed Beheer B.V.', 'particulier', NULL, NULL, NULL, 'Apeldoornseweg 43', NULL, 'ARNHEM', 'Nederland', '34217369.0', NULL, 'NL51 REVO 2865 8489 57', NULL),
    ('EU Facility Services', 'particulier', NULL, 'inkoopfacturen@houseofcovebo.nl', NULL, 'Ambachtsstraat 13', NULL, 'NIJKERK', 'Nederland', '32110787.0', NULL, 'NL94 ABNA 0254 3837 93', NULL),
    ('IFC B.V.', 'particulier', NULL, 'administratie@ifc.nl', NULL, 'Fruiteniersstraat 12', NULL, 'ZWIJNDRECHT', 'Nederland', '63659832.0', NULL, 'NL67 ABNA 0446 9231 68', NULL),
    ('Profectus Staffing Solutions', 'particulier', NULL, 'u.tevkir@carriere.com', NULL, 'Gastelseweg 144 F', NULL, 'ROOSENDAAL', 'Nederland', '83528865.0', NULL, 'NL31 RABO 0371 5511 10', NULL),
    ('J. Luijsterburg', 'particulier', NULL, 'j.luijsterburg@planet.nl', NULL, 'Nassaulaan 39', NULL, 'Steenbergen NB', 'Nederland', NULL, NULL, 'NL21 INGB 0008 3555 13', NULL),
    ('Jan Luijsterburg Beheer B.V.', 'particulier', NULL, 'j.luijsterburg@planet.nl', NULL, 'Nassaulaan 39', NULL, 'STEENBERGEN', 'Nederland', '20149379.0', NULL, 'NL21 INGB 0008 3555 13', NULL),
    ('J. Kuipers', 'particulier', NULL, 'kuipers.jordi@gmail.com', NULL, 'Luytkemeer 11', NULL, 'Heerenveen', 'Nederland', NULL, NULL, 'NL43 RABO 0330 9122 59', NULL),
    ('T. van de Moosdijk', 'particulier', NULL, 'tvandemoosdijk@gmail.com', NULL, 'Fliere 8', NULL, 'Gemert', 'Nederland', NULL, NULL, 'NL87 BUNQ 2059 0465 99', NULL),
    ('D. Walma', 'particulier', NULL, 'info@timmerbedrijfwalma.nl', NULL, 'Ceresweg 46-C', NULL, 'Leeuwarden', 'Nederland', NULL, NULL, 'NL08 RABO 0374 0135 78', NULL),
    ('G.D. Dijkstra', 'particulier', NULL, 'info@wijzerinwonen.nl', NULL, 'Zuurstukken 86', NULL, 'Eelde', 'Nederland', NULL, NULL, 'NL76 INGB 0662 5063 24', NULL),
    ('B. Bosch', 'particulier', NULL, 'brucebosch@live.nl', NULL, 'Stuartweg 29', NULL, 'Vianen', 'Nederland', NULL, NULL, 'NL18 INGB 0796 0357 25', NULL),
    ('H.T.C. Facility Services B.V.', 'particulier', NULL, 'inkoop@htcfacilityservices.nl', NULL, 'Rivium Quadrant 2', NULL, 'Capelle aan den IJssel', 'Nederland', '70962499.0', NULL, 'NL43 RABO 0358 2186 32', NULL),
    ('DB woonruimtebemiddeling', 'particulier', NULL, 'uren@dbgroup.nl', NULL, 'Vonderweg 29', NULL, 'ENTER', 'Nederland', '8108140.0', NULL, 'NL67 ABNA 0400 8375 95', NULL),
    ('IC Idea Complex Sp. Z.o.o.', 'particulier', NULL, 'invoice@ideacomplex.eu', NULL, 'ul. Oleska 97H/4', NULL, 'Opole', 'Polen', NULL, NULL, 'PL87 1050 1504 1000 0090 8038 5108', NULL),
    ('W.T. Bosgraaf en E. Stam', 'particulier', NULL, 'info@nerom-industrial.nl', NULL, 'Eerste Weteringdwarsstraat 75', NULL, 'Amsterdam', 'Nederland', NULL, NULL, 'NL50 ABNA 0106 0406 42', NULL),
    ('Autodaxx B.V.', 'particulier', NULL, 'inkoopfactuur@autodaxx.nl', NULL, 'Argon 21', NULL, 'OUD GASTEL', 'Nederland', '58795928.0', NULL, 'NL24 INGB 0008 6453 92', NULL),
    ('H. Molla Farajzadeh', 'particulier', NULL, 'habibmf@2ops.nl', NULL, 'Juttepeer 60', NULL, 'Den Hoorn ZH', 'Nederland', NULL, NULL, 'NL45 ABNA 0599 1094 83', NULL),
    ('Easyjob People', 'particulier', NULL, 'administratie@easyjobpeople.nl', NULL, 'Laanweg 6', NULL, 'SPIJKENISSE', 'Nederland', '24372176.0', NULL, 'NL23 RABO 0351 6588 82', NULL),
    ('Robert L.P. de Jonge', 'particulier', NULL, 'robertdejonge@ziggo.nl', NULL, 'Noolseweg 23', NULL, 'Blaricum', 'Nederland', NULL, NULL, 'NL48 RABO 0334 9161 35', NULL),
    ('Eizema Heerenveen Vastgoed b.v.', 'particulier', NULL, 'administratie@eizema-vastgoed.nl', NULL, 'Burgemeester Falkenaweg 36', NULL, 'HEERENVEEN', 'Nederland', '1114324.0', NULL, 'NL58 INGB 0660 8505 67', NULL),
    ('dockHolland Huisvesting B.V.', 'particulier', NULL, 'inkoopfacturen@dockholland.com', NULL, 'Industrieweg 130A', NULL, 'Rotterdam', 'Nederland', '24255227.0', NULL, 'NL65 ABNA 0892 0134 27', NULL),
    ('Fam. Derwig', 'particulier', NULL, 'hans.derwig@dunlopcb.com', NULL, 'Hooizolder 188', NULL, 'Drachten', 'Nederland', NULL, NULL, 'NL90 INGB 0001 0215 56', NULL),
    ('T. Hoolhorst', 'particulier', NULL, 't.hoolhorst@gmail.com', NULL, 'Leliestraat 21', NULL, 'Utrecht', 'Nederland', NULL, NULL, 'NL13 KNAB 0405 5294 14', NULL),
    ('E.C. Laus (Landsteinerhof 68)', 'particulier', NULL, NULL, NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, 'NL35 RABO 0199 2573 10', NULL),
    ('Werckpost Service B.V.', 'particulier', NULL, 'facturen@werckpost.nl', NULL, 'Het Rif 1', NULL, 'URK', 'Nederland', '64653986.0', NULL, NULL, NULL),
    ('A.I.G. Lukkien', 'particulier', NULL, NULL, NULL, 'Achterstekamp 28', NULL, 'Stadskanaal', 'Nederland', NULL, NULL, 'NL79 ABNA 0625 3594 96', NULL),
    ('Dutch Shipyard B.V.', 'particulier', NULL, 'info@dutchshipyard.eu', NULL, 'Bollenmarkt 6 C', NULL, 'ZWAAGDIJK-OOST', 'Nederland', '69474907.0', NULL, NULL, NULL),
    ('Meerdervoort Queda Real B.V.', 'particulier', NULL, 'chris@L-5.nl', NULL, 'Kranenburgweg 131', NULL, '''S-GRAVENHAGE', 'Nederland', '68918593.0', NULL, NULL, NULL),
    ('Nerom Industrial Flex B.V.', 'particulier', NULL, 'info@nerom-industrial.nl', NULL, 'Bouwkamp 9', NULL, 'NIEUWEHORNE', 'Nederland', '80543901.0', NULL, 'NL54 INGB 0006 7051 43', NULL),
    ('InAxtion Vastgoed B.V.', 'particulier', NULL, 'Invoice.vastgoed@inaxtion.com', NULL, 'Wijnstraat 123', NULL, 'Dordrecht', 'Nederland', '16074829.0', NULL, 'NL68 ABNA 0427 9222 08', NULL),
    ('TNM Vastgoed B.V.', 'particulier', NULL, 'tunny.10@hotmail.com', NULL, 'Vlietskade 9015', NULL, 'ARKEL', 'Nederland', '84774401.0', NULL, 'NL48 RABO 0397 2183 62', NULL),
    ('St. Zakelijke Beh.rek. Dijkstra Vastgoedbeh.', 'particulier', NULL, NULL, NULL, 'Berglaan 14', NULL, 'DRACHTEN', 'Nederland', '82743398.0', NULL, 'NL28 RABO 0368 1239 60', NULL),
    ('DS People B.V.', 'particulier', NULL, 'Facturen@dspeople.nl', NULL, 'Deltageul 13', NULL, 'STELLENDAM', 'Nederland', '63134462.0', NULL, NULL, NULL),
    ('Dhr. A. Ros', 'particulier', NULL, 'invoice-alex@hotmail.com', NULL, 'Slenerbrink 96', NULL, 'Emmen', 'Nederland', NULL, NULL, 'NL06 ABNA 0476 9393 64', NULL),
    ('O.Vasiutina', 'particulier', NULL, 'olga.vasiutina@asml.com', NULL, 'Molenstraat 16', NULL, 'Waalre', 'Nederland', NULL, NULL, 'NL75 INGB 0747 8086 27', NULL),
    ('O.P.H. Verhuur B.V. / Eigenaar.nl', 'particulier', NULL, 'info@eigenaar.nl', NULL, 'Willemskade 3', NULL, 'LEEUWARDEN', 'Nederland', '73003069.0', NULL, 'NL08 INGB 0390 6302 25', NULL),
    ('Dhr. B. Vlastuin', 'particulier', NULL, 'bartvlastuin@gmail.com', NULL, 'Reebaa 24', NULL, 'Scherpenzeel GL', 'Nederland', NULL, NULL, 'NL47 KNAB 0614 0994 63', NULL),
    ('Dhr. SWJ Colpaert en Mevr. J. Michielsen', 'particulier', NULL, 'info@jettymichielsen.com', NULL, 'Wilhelmina Druckerstraat 68', NULL, 'Coevorden', 'Nederland', NULL, NULL, 'NL56 INGB 0652 0926 67', NULL),
    ('Joyce Bakker Advies', 'particulier', NULL, 'joyce@joycebakker.nl', NULL, 'Mient 110', NULL, '''s-Gravenhage', 'Nederland', '60240156.0', NULL, NULL, NULL),
    ('Dhr. R. Bekken', 'particulier', NULL, 'renzo.bekken@gmail.com', NULL, 'Roemer Visscherlaan 57', NULL, 'Zeist', 'Nederland', NULL, NULL, 'NL62 BUNQ 2070 7468 01', NULL),
    ('Habroko B.V.', 'particulier', NULL, 'fdenbroeder@upcmail.nl', NULL, 'Valkenlaan 37', NULL, 'OOSTVOORNE', 'Nederland', '86020625.0', NULL, 'NL67 HAND 0785 1044 10', NULL),
    ('De Witte Brigade B.V.', 'particulier', NULL, 'administratie@wittebrigade.nl', NULL, 'Admiraliteitskade 79', NULL, 'ROTTERDAM', 'Nederland', '67474950.0', NULL, 'NL64 INGB 0007 5538 10', NULL),
    ('H.A. Samsom & M.E.P. Knaap', 'particulier', NULL, 'office@inmotionvastgoed.nl', NULL, 'Klokkenberg 88', NULL, 'Breda', 'Nederland', NULL, NULL, 'NL47 ABNA 0822 9350 07', NULL),
    ('F. Veurink en P. Neleman', 'particulier', NULL, NULL, NULL, 'Dorresteinseweg 18', NULL, 'Amersfoort', 'Nederland', NULL, NULL, 'NL62 INGB 0654 9954 78', NULL),
    ('Lion Trading', 'particulier', NULL, 'i.asadi@liontrading.nl', NULL, 'Tonneboerstraat 33', NULL, 'ROCKANJE', 'Nederland', '72344849.0', NULL, NULL, NULL),
    ('Eastmen Human Resources B.V.', 'particulier', NULL, 'facturen@eastmen.eu', NULL, 'Papendorpseweg 99', NULL, 'Utrecht', 'Nederland', '1117168.0', NULL, 'NL11 INGB 0669 4409 57', NULL),
    ('Central Job Facilities B.V.', 'particulier', NULL, 'invoice@centraljob.nl', NULL, 'Hoofdweg 649', NULL, 'HOOFDDORP', 'Nederland', '64022994.0', NULL, 'NL82 INGB 0007 0419 08', NULL),
    ('Flexvesting B.V.', 'particulier', NULL, 'administratie@flexvesting.com', NULL, 'Wiekenweg 50b', NULL, 'Amersfoort', 'Nederland', '83276491.0', NULL, 'NL51 RABO 0370 7195 57', NULL),
    ('''t Werkt B.V.', 'particulier', NULL, 'finance@twerkt.nl', NULL, 'Burgemeester Meslaan 98', NULL, 'TIEL', 'Nederland', '30234790.0', NULL, 'NL73 INGB 0674 0477 29', NULL),
    ('24/7 drive', 'particulier', NULL, 'factuur@247drive.nl', NULL, 'Ekkersrijt 7025', NULL, 'SON EN BREUGEL', 'Nederland', '17187408.0', NULL, NULL, NULL),
    ('Dhr. J.L. Meerding', 'particulier', NULL, 'jlmeerding@gmai.com', NULL, 'Mauvezand 6', NULL, 'Laren NH', 'Nederland', NULL, NULL, 'NL29 ABNA 0416 0042 29', NULL),
    ('Dhr. J.M.R. Boringa', 'particulier', NULL, 'rob@rohanvastgoed.nl', NULL, 'Willem Lodewijklaan 63', NULL, 'Heerenveen', 'Nederland', NULL, NULL, 'NL02 ABNA 0249 4453 36', NULL),
    ('J. J. van Veen', 'particulier', NULL, 'jack@obend.nl', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, NULL, NULL),
    ('Detaconcept Uitzendgroep B.V.', 'particulier', NULL, NULL, NULL, '''s-Gravenzandseweg 6', NULL, 'WATERINGEN', 'Nederland', '65815726.0', NULL, NULL, NULL),
    ('Detaconcept Services B.V.', 'particulier', NULL, 'paul@detaconcept.nl', NULL, '''s-Gravenzandseweg 4', NULL, 'WATERINGEN', 'Nederland', '72041749.0', NULL, 'NL35 INGB 0008 3668 04', NULL),
    ('Mw. M. Hyllested Poulsen en Dhr. S. Crull', 'particulier', NULL, 'maria-sander@outlook.com', NULL, 'Ina Boudier-Bakkerhof 18', NULL, 'Utrecht', 'Nederland', NULL, NULL, 'NL95 ABNA 0102 0651 60', NULL),
    ('Vlot Vastgoed B.V.', 'particulier', NULL, 'jan@wassenaarvastgoed.nl', NULL, 'Pontdyk 8 c', NULL, 'LANGWEER', 'Nederland', '61769193.0', NULL, 'NL36 RABO 0312 3427 05', NULL),
    ('Y. K. Bos', 'particulier', NULL, NULL, NULL, 'Europaplein 49', NULL, 'Stadskanaal', 'Nederland', NULL, NULL, 'NL62 RABO 0354 1315 83', NULL),
    ('E.C. Laus / K. van Elk Landsteinerhof', 'particulier', NULL, 'eva_laus@hotmail.com', NULL, 'Landsteinerhof 68', NULL, 'Hoogeveen', 'Nederland', NULL, NULL, 'NL48 ABNA 0562 3643 74', NULL),
    ('Dhr. M. Moeilijker', 'particulier', NULL, 'mmoeilijker@gmail.com', NULL, 'Hoofdstraat 77', NULL, 'Ovezande', 'Nederland', NULL, NULL, 'NL66 RABO 0346 0186 25', NULL),
    ('Dhr. R. J. Beking', 'particulier', NULL, 'rjbeking@icloud.com', NULL, 'Dauwbraam 31', NULL, 'KATWIJK', 'Nederland', NULL, NULL, 'NL32 RABO 0331 8091 25', NULL),
    ('Dhr. R Verspui', 'particulier', NULL, 'rverspui@hotmail.com', NULL, 'Peursumseweg 119a', NULL, 'Giessenburg', 'Nederland', NULL, NULL, 'NL51 RABO 0321 7135 08', NULL),
    ('D Blommers', 'particulier', NULL, 'd_blommers@hotmail.com', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, 'NL91 TRIO 0391 0901 78', NULL),
    ('Dhr. A. Dorin', 'particulier', NULL, 'rasinfra@hotmail.com', NULL, 'de Dulf 69', NULL, 'LEEUWARDEN', 'Nederland', NULL, NULL, NULL, NULL),
    ('MBS Services B.V.', 'particulier', NULL, 'info@mbs-services.nl', NULL, 'Dwarsweg 34', NULL, 'ROZENBURG', 'Nederland', '73615889.0', NULL, NULL, NULL),
    ('Vastgoed Spijkenisse', 'particulier', NULL, 'a.bilge@vastgoedspijkenisse.nl', NULL, 'Theemsweg 85', NULL, 'Spijkenisse', 'Nederland', '53388917.0', NULL, NULL, NULL),
    ('Gemeente Waadhoeke', 'particulier', NULL, 'info@waadhoeke.nl', NULL, 'Harlingerweg 18', NULL, 'Franeker', 'Nederland', '70528586.0', NULL, NULL, NULL),
    ('BDR Uitzendbureau B.V.', 'particulier', NULL, 'muratbayka@gmail.com', NULL, 'Sint-Andriesstraat 222', NULL, 'ROTTERDAM', 'Nederland', '24408919.0', NULL, 'NL14 INGB 0008 2350 68', NULL),
    ('Nerom Flex B.V.', 'particulier', NULL, 'administratie@nerom-bv.nl', NULL, 'Bouwkamp 9', NULL, 'NIEUWEHORNE', 'Nederland', '80543901.0', NULL, 'NL54 INGB 0006 7051 43', NULL),
    ('Bouw Service International B.V.', 'particulier', NULL, 'bouwserviceinternational@gmail.com', NULL, 'Kanaal Noord 446', NULL, 'BEEMTE BROEKLAND', 'Nederland', '78258901.0', NULL, NULL, NULL),
    ('Mooswijk T.R. & Plugers R.', 'particulier', NULL, 'tvandemoosdijk@gmail.com', NULL, 'Fliere 8', NULL, 'Gemert', 'Nederland', NULL, NULL, 'NL88 INGB 0626 5496 63', NULL),
    ('STANA d.o.o.', 'particulier', NULL, 'stana2@telemach.net', NULL, 'Razlagova 11', NULL, 'Maribor', 'Slovenië', NULL, NULL, 'SI56 0700 0000 3563 191', NULL),
    ('Dhr D. Pronk en Mw y. Pronk - Dijkhuizen', 'particulier', NULL, 'familiepronk-dijkhuizen@ziggo.nl', NULL, 'Aronskelkweg 70', NULL, '''s-Gravenhage', 'Nederland', NULL, NULL, 'NL93 INGB 0388 7726 97', NULL),
    ('RyanRent B.V.', 'particulier', NULL, 'facturen@ryanrent.nl', NULL, 'Energieweg 22 c', NULL, 'VLAARDINGEN', 'Nederland', '87946653.0', NULL, 'NL50 RABO 0339 0738 10', NULL),
    ('Tempsteel B.V.', 'particulier', NULL, 'm.matelis@tempsteel.eu', NULL, 'Paul Krugerstraat 12 H', NULL, 'ROTTERDAM', 'Nederland', '83196641.0', NULL, NULL, NULL),
    ('Marco van Beek B.V.', 'particulier', NULL, NULL, NULL, 'Ruxveenseweg 6', NULL, 'STEENWIJK', 'Nederland', '5070965.0', NULL, NULL, NULL),
    ('Euromontur Asemblies SL.', 'particulier', NULL, 'ana.gomez@euromontur.net', NULL, 'Merindad Castilla La Vieja 27', NULL, 'Spanje', 'Nederland', NULL, NULL, 'ES38 2085 4891 8203 3358 3866', NULL),
    ('Eigenaren van Dieptol 63', 'particulier', NULL, 'prkapper@gmail.com,judithdijkgraaf@hotmail.com', NULL, 'Dieptol 63', NULL, 'Steenwijk', 'Nederland', NULL, NULL, 'NL76 KNAB 0516 2255 53', NULL),
    ('Koens T. Dhr.', 'particulier', NULL, 'tommykoens@gmail.com', NULL, 'Krijnenweg 3', NULL, 'Bussum', 'Nederland', NULL, NULL, 'NL71 INGB 0652 0479 71', NULL),
    ('Fix Personeelsdiensten', 'particulier', NULL, 'admin@teamfix.nl', NULL, 'Leemidden 22', NULL, 'DE LIER', 'Nederland', '22065411.0', NULL, 'NL05 RABO 0312 4652 89', NULL),
    ('ZaMens R.I.A. B.V.', 'particulier', NULL, 'facturen@zamens.nl', NULL, 'Parmentierplein 20', NULL, 'ROTTERDAM', 'Nederland', '11069235.0', NULL, NULL, NULL),
    ('Dhr. T. Roestenberg en Mw. Roestenberg - Hustinx', 'particulier', NULL, 'timoroestenberg@hotmail.com', NULL, 'De Haarmansenk 7', NULL, 'Schalkhaar', 'Nederland', NULL, NULL, 'NL42 ASNB 8832 1748 71', NULL),
    ('Valkenet Vastgoed B.V.', 'particulier', NULL, NULL, NULL, 'Perkinsbaan 15 A', NULL, 'NIEUWEGEIN', 'Nederland', '69246025.0', NULL, 'NL61 INGB 0008 0361 48', NULL),
    ('M@tchm@kers International B.V.', 'particulier', NULL, 'hello@matchmakers.nu', NULL, 'Wichard van Pontlaan 86', NULL, 'ZALTBOMMEL', 'Nederland', '87011549.0', NULL, 'NL16 ABNA 0124 8353 92', NULL),
    ('KODE Staffhousing B.V.', 'particulier', NULL, 'administratie@kodere.nl', NULL, 'Economiestraat 16', NULL, 'Sittard', 'Nederland', '89585798.0', NULL, 'NL48 INGB 0389 9935 73', NULL),
    ('DIT en Larex Vakpersoneel B.V.', 'particulier', NULL, 'factuur@ditenlarexvakpersoneel.nl', NULL, 'Maagdenburgstraat 10', NULL, 'DEVENTER', 'Nederland', '8116290.0', NULL, 'NL17 RABO 0320 0278 72', NULL),
    ('Homescout21 B.V.', 'particulier', NULL, 'rene@homescout21.com', NULL, 'Keizerstraat 28 1', NULL, '''S-GRAVENHAGE', 'Nederland', '82780242.0', NULL, 'NL22 ABNA 0101 0258 58', NULL),
    ('TecFlex B.V.', 'particulier', NULL, 'jkoning@tecflex.nl', NULL, 'Emdenweg 3', NULL, 'GRONINGEN', 'Nederland', NULL, NULL, NULL, NULL),
    ('Employ Facilitair B.V.', 'particulier', NULL, 'facilitair@employ.nl', NULL, 'Industrieweg 1', NULL, 'HOOGEVEEN', 'Nederland', '68292449.0', NULL, 'NL28 RABO 0317 3858 79', NULL),
    ('Alpha Workforce Aps', 'particulier', NULL, 'operations@alphaworkforce.net', NULL, 'Priory Hall', NULL, 'Dublin', 'Ierland', NULL, NULL, NULL, NULL),
    ('Hiway Operational Company B.V.', 'particulier', NULL, 'lea@alphaworkforce.net', NULL, 'Kerkenbos 1075 W', NULL, 'NIJMEGEN', 'Nederland', '80604250.0', NULL, NULL, NULL),
    ('ICS Impianti S.R.L.', 'particulier', NULL, 'info@icsimpiantisrl.com', NULL, 'President Kennedylaan 19', NULL, '''S-GRAVENHAGE', 'Nederland', NULL, NULL, NULL, NULL),
    ('Suricare B.V.', 'particulier', NULL, 'arie.degroot@carevisie.nl', NULL, 'Kastanjelaan 8', NULL, 'VELP', 'Nederland', '83481699.0', NULL, NULL, NULL),
    ('Eemsdelta Housing B.V.', 'particulier', NULL, 'facturen@eemsdelta-housing.nl', NULL, 'Weereweg 25 A', NULL, 'TJUCHEM', 'Nederland', '80302246.0', NULL, 'NL22 INGB 0007 7428 43', NULL),
    ('De Uitlener B.V.', 'particulier', NULL, 'facturen@deuitlener.nl', NULL, 'Larenseweg 30', NULL, 'LOCHEM', 'Nederland', '60382694.0', NULL, NULL, NULL),
    ('Impes Service S.p.A.', 'particulier', NULL, 'fatture.olanda@impesservice.it, Nicola.pisani@impesservice.it', NULL, 'President Kennedylaan 19', NULL, '''s-Gravenhage', 'Nederland', NULL, NULL, NULL, NULL),
    ('R&E Services', 'particulier', NULL, 'administratie@rebv.nl', NULL, 'Rhijnspoor 225 B', NULL, 'CAPELLE AAN DEN IJSSEL', 'Nederland', NULL, NULL, 'NL53 ABNA 0640 1561 50', NULL),
    ('PersoneelDirectFriesland', 'particulier', NULL, 'info@personeeldirectfriesland.nl', NULL, 'Zenegroen 129', NULL, 'LEEUWARDEN', 'Nederland', '81961324.0', NULL, NULL, NULL),
    ('Autobedrijf Voorne', 'particulier', NULL, 'info@autobedrijfvoorne.nl', NULL, 'Langeweg 3', NULL, 'OOSTVOORNE', 'Nederland', NULL, NULL, NULL, NULL),
    ('Dhr I.B. Stefan', 'particulier', NULL, 'alexandrudorin93@gmail.com', NULL, 'de Dulf 69', NULL, 'LEEUWARDEN', 'Nederland', NULL, NULL, NULL, NULL),
    ('Jong de SAW Dhr', 'particulier', NULL, 'jcdejong@aol.nl', NULL, 'De Tolve 34', NULL, 'Goutum', 'Nederland', NULL, NULL, 'NL26 RABO 0111 5750 01', NULL),
    ('Bosch B Dhr (Scheepjesbrug 814 Meerkerk)', 'particulier', NULL, 'brucebosch@live.nl', NULL, 'Nolweg 9', NULL, 'Schelluinen', 'Nederland', NULL, NULL, 'NL47 BUNQ 2053 5805 93', NULL),
    ('Houvast Estates B.V.', 'particulier', NULL, 'hershihoffman22@gmail.com', NULL, 'Consciencestraat 47', NULL, 'Antwerpen', 'België', NULL, NULL, NULL, NULL),
    ('Heijdra Dhr. H.M.', 'particulier', NULL, 'h.heijdra@outlook.com', NULL, 'Lauwersmeer 22', NULL, 'Barendrecht', 'Nederland', NULL, NULL, 'NL81 INGB 0671 1964 64', NULL),
    ('Maatschap Van Driel - Vd Vlist', 'particulier', NULL, 'drielvlist@gmail.com', NULL, 'Hekendorpse Buurt 24', NULL, 'HEKENDORP', 'Nederland', '85563943.0', NULL, 'NL24 KNAB 0416 5382 31', NULL),
    ('Leen Bakker Nederland B.V.', 'particulier', NULL, NULL, NULL, 'Karperweg 3', NULL, 'RAAMSDONKSVEER', 'Nederland', '18118971.0', NULL, 'NL72 RABO 0320 2430 95', NULL),
    ('H. van den Berg', 'particulier', NULL, 'martijnbergvanden@gmail.com', NULL, 'Marconistraat 12', NULL, 'Huizen', 'Nederland', NULL, NULL, 'NL72 BUNQ 2036 4253 05', NULL),
    ('FlexState B.V.', 'particulier', NULL, 'customer-success@hiway-mail.com', NULL, 'Kerkenbos 1075 W', NULL, 'NIJMEGEN', 'Nederland', NULL, NULL, NULL, NULL),
    ('Ras R.A. Dhr.', 'particulier', NULL, 'ron.ras1999@outlook.com', NULL, 'Laan van Nieuw Blankenburg 328', NULL, 'Rozenburg ZH', 'Nederland', NULL, NULL, 'NL80 RABO 0356 6418 13', NULL),
    ('Labour Housing BV', 'particulier', NULL, 'crediteuren@ottoworkforce.eu', NULL, 'Postbus 5145', NULL, 'VENRAY', 'Nederland', NULL, NULL, 'NL84 ABNA 0405 8514 13', NULL),
    ('THS EU B.V.', 'particulier', NULL, 'invoices@tecline.com', NULL, 'Paasheuvelweg 34 A', NULL, 'AMSTERDAM', 'Nederland', '2333810.0', NULL, NULL, NULL),
    ('NL Realty B.V.', 'particulier', NULL, 'administratie@nl-jobs.com', NULL, 'Honderdland 1', NULL, 'MAASDIJK', 'Nederland', NULL, NULL, 'NL90 RABO 0346 4019 25', NULL),
    ('AKT Autoschade', 'particulier', NULL, 'facturen@aktautoschade.com', NULL, 'Goirkekanaaldijk 211-18', NULL, 'Tilburg', 'Nederland', NULL, NULL, NULL, NULL),
    ('MPC Energy B.V.', 'particulier', NULL, 'randolf@hollandhousing.work', NULL, 'Franse Akker 8', NULL, 'BREDA', 'Nederland', '74896482.0', NULL, NULL, NULL),
    ('M van den Berg e/o H van den Berg', 'particulier', NULL, 'martijnbergvanden@gmail.com', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, 'NL61 BUNQ 2100 6227 22', NULL),
    ('Impianti Industriala S.P.A. NEDERLAND BRANCH', 'particulier', NULL, 'vendors@sitie.it', NULL, 'Poortland 66', NULL, 'Amsterdam', 'Nederland', NULL, NULL, NULL, NULL),
    ('BJ Bakker', 'particulier', NULL, 'bjbakker85@hotmail.com', NULL, 'Spiens 3', NULL, 'Dokkum', 'Nederland', NULL, NULL, 'NL36 RABO 0302 0165 70', NULL),
    ('AKRION ADMINISTRATION', 'particulier', NULL, 'info@interm-project.com', NULL, 'Corn. Speelmanstraat 77', NULL, '''s-Gravenhage', 'Nederland', NULL, NULL, NULL, NULL),
    ('Techvisie Personeelsdiensten Centraal B.V.', 'particulier', NULL, 'facturen@techvisie.nl', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, NULL, NULL),
    ('UAB Baltic Contracting Group', 'particulier', NULL, 'Kristina.domarkaite@baltcontract.eu', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, NULL, NULL),
    ('UAB „Laivsta“/ JSC „Laivsta“, Part of Litana Group', 'particulier', NULL, 'aleksej.frolov@litana-group.com', NULL, 'Verslo str. 6', NULL, 'Klaipeda, Lithuania', 'Litouwen', NULL, NULL, NULL, NULL),
    ('Housing en Transport Facilities B.V.', 'particulier', NULL, 'inkoopfacturen@houseofcovebo.nl', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, NULL, NULL),
    ('Aelbers Flexibele Personeels Diensten B.V.', 'particulier', NULL, 'facturen@aelberspersoneel.nl', NULL, 'Grutbroek 15', NULL, 'Doetinchem', 'Nederland', NULL, NULL, 'NL65 INGB 0662 8126 54', NULL),
    ('Karadeniz Diensten', 'particulier', NULL, 'info@karadenizdiensten.nl', NULL, 'Bomendijk 10', NULL, 'Rozenburg ZH', 'Nederland', NULL, NULL, NULL, NULL),
    ('Adecco Group', 'particulier', NULL, 'crediteurenadministratie@adecco.nl', NULL, NULL, NULL, 'Zaltbommel', 'Nederland', NULL, NULL, NULL, NULL),
    ('ABC Bedrijfsservice B.V', 'particulier', NULL, 'randy@abc-jobs.eu', NULL, 'Sint Canisiussingel 36', NULL, 'Nijmegen', 'Nederland', NULL, NULL, 'NL04 RABO 0344 4836 49', NULL),
    ('D Kleijweg', 'particulier', NULL, 'devinkleijweg@hotmail.com', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, 'NL48 RABO 0358 2190 27', NULL),
    ('Maytree Invest', 'particulier', NULL, 'leon@maytreeme.nl', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, 'NL17 INGB 0006 9360 87', NULL),
    ('Facili Flex BV', 'particulier', NULL, 'invoice@ifj.nl', NULL, 'Legmeerdijk 313', NULL, 'Aalsmeer', 'Nederland', NULL, NULL, 'NL68 RABO 0330 6682 42', NULL),
    ('Transport People B.V.', 'particulier', NULL, 'facturenaalsmeer@transportpeople.nl', NULL, 'Tiendweg 24', NULL, 'Naaldwijk', 'Nederland', NULL, NULL, NULL, NULL),
    ('J. Hogervorst', 'particulier', NULL, 'jan@hoger.demon.nl', NULL, 'Molendijk 3', NULL, 'Pijnacker', 'Nederland', NULL, NULL, 'NL46 RABO 0354 4717 59', NULL),
    ('Dumanli', 'particulier', NULL, NULL, NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, 'NL10 INGB 0637 6346 75', NULL),
    ('Lievaart B.V.', 'particulier', NULL, 'vl-beheer@outlook.com', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, 'NL52 KNAB 0512 2396 73', NULL),
    ('Parkwonen', 'particulier', NULL, 'info@parkwonen.nl', NULL, 'Kruisplein 488A', NULL, 'Rotterdam', 'Nederland', NULL, NULL, 'NL04 RABO 0307 5644 79', NULL),
    ('Gap Costruzioni Dutch Branch', 'particulier', NULL, 'invoice@gapcostruzioni.it', NULL, 'Posthoornstraat 11', NULL, 'Rotterdam', 'Nederland', NULL, NULL, 'IT29 E030 6984 6201 0000 0011 940', NULL),
    ('Looije Facilities B.V.', 'particulier', NULL, 'Factuur@nwg.nl', NULL, 'Verburghlaan 24 a', NULL, 'Poeldijk', 'Nederland', NULL, NULL, NULL, NULL),
    ('Head Vastgoed B.V.', 'particulier', NULL, 'administratie@headstaffing.nl', NULL, 'Edisonbaan 12', NULL, 'Nieuwegein', 'Nederland', NULL, NULL, 'NL72 RABO 0313 2276 67', NULL),
    ('Feel Flex B.V.', 'particulier', NULL, 'factuur@feelflex.nl', NULL, 'Doornhoek 3842', NULL, 'Veghel', 'Nederland', NULL, NULL, NULL, NULL),
    ('Orange Investments Group B.V.', 'particulier', NULL, 'crediteuren@peopledirekt.nl', NULL, 'Leehove 80', NULL, 'De Lier', 'Nederland', NULL, NULL, 'NL43 RABO 0197 7933 39', NULL),
    ('MC Mostert prive', 'particulier', NULL, 'arie@tradiro.nl', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, 'NL55 RABO 0318 2923 43', NULL),
    ('Betterway BV', 'particulier', NULL, 'rbecker@fbaivastgoed.com', NULL, 'Nijverheidsweg-Noord 81', NULL, 'Amersfoort', 'Nederland', NULL, NULL, NULL, NULL),
    ('Flextalent4u Uitzenden B.V.', 'particulier', NULL, 'administratie@flextalent4u.nl', NULL, 'Manmakerweg 23', NULL, 'Bleskensgraaf Ca', 'Nederland', NULL, NULL, NULL, NULL),
    ('A. Brouwers en S. Brouwers- van Weert', 'particulier', NULL, NULL, NULL, 'Dokter Barentsenstraat 42', NULL, 'Bergeyk', 'Nederland', NULL, NULL, 'NL36 BUNQ 2101 3885 02', NULL),
    ('People21 Services BV', 'particulier', NULL, 'administratie@people21.eu', NULL, 'Westfrankelandsedijk 7', NULL, 'Schiedam', 'Nederland', NULL, NULL, NULL, NULL),
    ('Works Personeelsdiensten', 'particulier', NULL, 'info@works.jobs', NULL, 'Kerkenbos 1051', NULL, 'Nijmegen', 'Nederland', NULL, NULL, NULL, NULL),
    ('WILL Vakkrachten B. V.', 'particulier', NULL, 'administratie@wilgroep.nl', NULL, 'Streekweg 22', NULL, 'Nijmegen', 'Nederland', NULL, NULL, NULL, NULL),
    ('Houses2Rent', 'particulier', NULL, 'info@houses2rent.nl', NULL, 'Stellingmolen 42', NULL, 'Maassluis', 'Nederland', NULL, NULL, 'NL17 INGB 0390 7692 58', NULL),
    ('Bouius', 'particulier', NULL, 'r.bouius@hotmail.com', NULL, 'Jan van Scorelstraat 50', NULL, 'Leeuwarden', 'Nederland', NULL, NULL, 'NL25 RABO 0310 2297 58', NULL),
    ('JPJ Stoel', 'particulier', NULL, 'jpstoel@gmail.com', NULL, 'Celesta 16', NULL, 'Kampen', 'Nederland', NULL, NULL, 'NL60 HAND 0787 3890 80', NULL),
    ('GSI B.V.', 'particulier', NULL, 'maurice@teamwanted.nl', NULL, 'Koperslagersstraat 88', NULL, 'Sneek', 'Nederland', NULL, NULL, NULL, NULL),
    ('Desa Construction NL BV', 'particulier', NULL, 'invoices.nl@desacons.eu', NULL, 'Lange Kleiweg 26e', NULL, 'Rijswijk ZH', 'Nederland', NULL, NULL, NULL, NULL),
    ('EG Facility & Services BV', 'particulier', NULL, 'facturen@egfs.nl', NULL, 'Velsenstraat 6A', NULL, 'Werkendam', 'Nederland', '88802957.0', NULL, 'NL69 RABO 0359 9345 79', NULL),
    ('PMM Workforce Management Ltd', 'particulier', NULL, 'd.soare@pmm-group.eu , accounting@pmm-group.eu', NULL, 'Triq ix-Xatt 154, Level 2, Office A', NULL, 'Gzira', 'Malta', NULL, NULL, NULL, NULL),
    ('Dunaj Projekty SRO', 'particulier', NULL, 'pim.stroo@dunajprojekty.eu', NULL, 'Velkoblahosvska cesta 1063/5 929 01', NULL, 'Dunajska Streda', 'Slowakije', NULL, NULL, NULL, NULL),
    ('GMC KOVI Global Metal Construction', 'particulier', NULL, 'emina.dzelilovic@gmcgroup.ba', NULL, 'Maistrova ulica 16', NULL, 'Kanik', 'Slovenië', NULL, NULL, NULL, NULL),
    ('Team Technical Services BV', 'particulier', NULL, 'robert@team-ts.nl', NULL, 'Marrewijklaan 11', NULL, 'Spijkenisse', 'Nederland', NULL, NULL, NULL, NULL),
    ('EWLIT Sp.Z.O.O.SP.K', 'particulier', NULL, 'Michal.wierzchowski@ewl.com.pl', NULL, 'ul. Kilinskiego 16/6', NULL, 'Piaseczno', 'Polen', NULL, NULL, NULL, NULL),
    ('Mavi Vastgoed', 'particulier', NULL, 'invoice@mavivastgoed.nl', NULL, 'Havenstraat 20', NULL, 'Ridderkerk', 'Nederland', NULL, NULL, NULL, NULL),
    ('Gastvrijaanzee.nl', 'particulier', NULL, 'rekening@getstay.nl', NULL, 'Mosselaan 53', NULL, 'Egmond aan den Hoef', 'Nederland', NULL, NULL, 'NL78 INGB 0006 3933 41', NULL),
    ('Van Bergen Personeelsdiensten B.V.', 'particulier', NULL, 'facturen@aubvanbergen.nl', NULL, 'Honderdland 960', NULL, 'Maasdijk', 'Nederland', NULL, NULL, NULL, NULL),
    ('Oranjegroep Vastgoed B.V.', 'particulier', NULL, 'inkoopfacturen@oranjegroepvastgoed.nl', NULL, 'van Vollenhovenstraat 10', NULL, 'Rotterdam', 'Nederland', NULL, NULL, NULL, NULL),
    ('Team Unica B.V.', 'particulier', NULL, 'facturen@teamunica.nl', NULL, 'Langeweg 15B', NULL, 'Oostvoorne', 'Nederland', NULL, NULL, NULL, NULL),
    ('UAB Toromega', 'particulier', NULL, 'dovydas.j@toromega.eu', NULL, 'Danes g.6', NULL, 'Klaipeda', 'Litouwen', NULL, NULL, NULL, NULL),
    ('C-Flex B.V.', 'particulier', NULL, 'administratie@cflexbv.nl', NULL, 'Kerkenbos 1051', NULL, 'Nijmegen', 'Nederland', NULL, NULL, NULL, NULL),
    ('house of work', 'particulier', NULL, 'rob.jansen@houseofwork.nl', NULL, 'Stoelmatter 38', NULL, 'Wateringen', 'Nederland', NULL, NULL, NULL, NULL),
    ('Focuzop-eu', 'particulier', NULL, 'administratie@focuzop-eu.com', NULL, 'Amperestraat 7-14', NULL, 'Harderwijk', 'Nederland', NULL, NULL, NULL, NULL),
    ('Johan van der Burg', 'particulier', NULL, 'johanvanderburg87@gmail.com', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, 'NL74 RABO 0134 5913 64', NULL),
    ('Mediterranean Careers Netherlands B.V.', 'particulier', NULL, 'finance@mcareers.eu', NULL, 'Bredaseweg 185', NULL, 'Etten-Leur', 'Nederland', NULL, NULL, NULL, NULL),
    ('Soul inn B.B B.V', 'particulier', NULL, 'ed@edwinroos.com', NULL, 'Oude Delft', NULL, 'Delft', 'Nederland', NULL, NULL, NULL, NULL),
    ('Maria', 'particulier', NULL, 'calinmariana@rambler.ru', NULL, 'Sparrendreef 15', NULL, 'Vlaardingen', 'Nederland', NULL, NULL, NULL, NULL),
    ('In Stijl Totaalbouw BV', 'particulier', NULL, 'info@instijltotaalbouw.nl', NULL, 'Burgemeester Freijterslaan 1', NULL, 'Roosendaal', 'Nederland', NULL, NULL, NULL, NULL),
    ('MDI Techniek B.V.', 'particulier', NULL, 'wendy@mditechniek.nl', NULL, 'Parallelweg 31', NULL, 'Neede', 'Nederland', NULL, NULL, 'NL89 RABO 0136 1461 98', NULL),
    ('JC Kemp', 'particulier', NULL, NULL, NULL, 'Spijksesteeg 1', NULL, 'Spijk Gem Lingewaal', 'Nederland', NULL, NULL, 'NL53 RABO 0322 2526 95', NULL),
    ('Uitzendbureau Bakker B.V.', 'particulier', NULL, 'administratie@bedrijvenbakker.nl', NULL, 'Albertjoachimkade 33H', NULL, 'Goes', 'Nederland', NULL, NULL, NULL, NULL),
    ('I.T.S. SR.L. (INDUSTRIAL TECHNICAL SERVICES), BRAN', 'particulier', NULL, 'salvotringali@hotmail.it , dballotta@itsservices.it', NULL, 'Schepenenweg 35', NULL, 'oostvoorne', 'Nederland', NULL, NULL, NULL, NULL),
    ('JES Funding & Beheer B.V.', 'particulier', NULL, 'info@jesbeheer.com', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, 'NL79 INGB 0008 0477 55', NULL),
    ('Thuisvesting B.V.', 'particulier', NULL, 'facturen@thuisvesting.com', NULL, 'Barneveldsestraat 44', NULL, 'Renswoude', 'Nederland', NULL, NULL, NULL, NULL),
    ('A.H.S. Willemsen', 'particulier', NULL, 'huurwoningarnhem@gmail.com', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, 'NL90 ABNA 0861 1395 26', NULL),
    ('JJM Personeel B.V.', 'particulier', NULL, 'Facturen@jjmpersoneel.nl', NULL, 'van Leeuwenhoekweg 6', NULL, 'Schijndel', 'Nederland', NULL, NULL, 'NL77 RABO 0329 2174 45', NULL),
    ('Royal DS Personeel-service', 'particulier', NULL, 'm.langeveld@royalds.nl', NULL, 'Ambachtsweg 57', NULL, 'Nijmegen', 'Nederland', NULL, NULL, NULL, NULL),
    ('VALO Facilities B.V.', 'particulier', NULL, 'invoices.facilities@valo-group.eu', NULL, 'Bruistensingel 400', NULL, '''s-Hertogenbosch', 'Nederland', NULL, NULL, NULL, NULL),
    ('Jacco Maat', 'particulier', NULL, 'jacco@jtvastgoed.nl', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, NULL, NULL),
    ('Holland Chalet Park', 'particulier', NULL, 'Receptie@hollandchaletpark.nl', NULL, 'Kerkweg 9a', NULL, 'Hensbroek', 'Nederland', NULL, NULL, 'NL28 INGB 0000 0643 12', NULL),
    ('Europe-jobs B.V.', 'particulier', NULL, 'info@europe-jobs.nl', NULL, 'Oude Terborgseweg 288', NULL, 'Doetinchem', 'Nederland', NULL, NULL, 'NL42 INGB 0674 8319 50', NULL),
    ('WIL International B.V.', 'particulier', NULL, 'international@wilgroep.nl', NULL, 'Streekweg 22', NULL, 'Nijmegen', 'Nederland', NULL, NULL, NULL, NULL),
    ('HousingWell B.V.', 'particulier', NULL, 'info@housingwell.nl', NULL, 'Tinstraat 7b', NULL, 'Ridderkerk', 'Nederland', NULL, NULL, NULL, NULL),
    ('P. Nederstigt', 'particulier', NULL, 'p.nederstigt@casema.nl', NULL, 'Frans Halsstraat 67', NULL, 'Lisse', 'Nederland', NULL, NULL, 'NL30 ABNA 0401 3982 42', NULL),
    ('Welcome Housing B.V.', 'particulier', NULL, 'Invoices@hobij.nl', NULL, 'Heilig Hartplein 1', NULL, 'Veghel', 'Nederland', NULL, NULL, NULL, NULL),
    ('Verlangen Finance BV', 'particulier', NULL, 'info@verlangenfinance.nl', NULL, 'Touwbaan 1', NULL, 'Gorinchem', 'Nederland', NULL, NULL, NULL, NULL),
    ('G.K. Stoel', 'particulier', NULL, 'rolfstoel@hotmail.com', NULL, 'Patrijsstraat 39', NULL, 'Papendrecht', 'Nederland', NULL, NULL, NULL, NULL),
    ('Timing Uitzendteam BV', 'particulier', NULL, 'inkoopfacturen@timing.nl', NULL, 'Deventerstraat 15-2', NULL, 'Apeldoorn', 'Nederland', NULL, NULL, 'NL48 INGB 0651 8897 90', NULL),
    ('SS Kara Yacht Painters LLP', 'particulier', NULL, 'sskarayaght23@gmail.com', NULL, 'Omonias 77', NULL, 'Kavala', 'Griekenland', NULL, NULL, NULL, NULL),
    ('E Rebel', 'particulier', NULL, 'erebel@ziggo.nl', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, 'NL66 INGB 0004 1170 64', NULL),
    ('Dutch Ink', 'particulier', NULL, 'Info@dutchink.nl', NULL, 'George Stephensonweg 21m', NULL, 'Vlaardingen', 'Nederland', NULL, NULL, NULL, NULL),
    ('IPS Industrial Plant Solutions Kft.', 'particulier', NULL, 'loretta.hanoder@ipsolutions.hu', NULL, 'Lage Mosten 49', NULL, 'Breda', 'Nederland', NULL, NULL, NULL, NULL),
    ('Estra Logistics Systems B.V.', 'particulier', NULL, 'finance@cruisr.nl', NULL, 'Zuid Hollandiaan 7', NULL, '''s-Gravenhage', 'Nederland', NULL, NULL, NULL, NULL),
    ('Fareon Z Nederland', 'particulier', NULL, 'nancy@fareon.nl', NULL, 'Lange Amerikaweg 67', NULL, 'Apeldoorn', 'Nederland', NULL, NULL, 'NL50 ABNA 0838 0539 55', NULL),
    ('Horus Team Sp. Z.o.o.', 'particulier', NULL, 'administration@horusteam.net', NULL, 'Święty Marcin 29/8', NULL, 'Poznan', 'Polen', NULL, NULL, NULL, NULL),
    ('Kleijweg projects', 'particulier', NULL, 'Info@kleijweginvestments.nl', NULL, 'Zwedenstraat 12', NULL, 'De Lier', 'Nederland', NULL, NULL, NULL, NULL),
    ('Multiservizi Romania SRL', 'particulier', NULL, 'amministrazionepythagoras@gmail.com', NULL, 'Sector 1 str academiei nr 35-37 scb et2', NULL, 'Bucuresti', 'Roemenië', NULL, NULL, NULL, NULL),
    ('FGM Solar Renewable S.R.L.', 'particulier', NULL, 'edeny2002@gmail.com', NULL, 'Str. Nufarului, Nr. 28E, Et. 3', NULL, 'Oradea', 'Roemenië', NULL, NULL, NULL, NULL),
    ('S. Kleiren', 'particulier', NULL, 'sabine.kleiren@gmail.com', NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, 'NL20 RABO 0103 8768 98', NULL),
    ('4 Homes B.V.', 'particulier', NULL, 'factuur@4homes.nl', NULL, 'Prins Reinierstraat 18a', NULL, 'Steenbergen', 'Nederland', NULL, NULL, 'NL30 RABO 0120 4592 56', NULL),
    ('Twins BV', 'particulier', NULL, 'info@twinsbv.com', NULL, 'Burgemeester Letteweg 31', NULL, 'Oostvoorne', 'Nederland', NULL, NULL, 'NL79 INGB 0107 5053 47', NULL),
    ('RNDV Industries', 'particulier', NULL, 'laura.brackiene@rndv.eu', NULL, 'Taikos pr. 52C', NULL, 'Klipeda', 'Litouwen', NULL, NULL, NULL, NULL),
    ('UAB Techsome', 'particulier', NULL, 'info@techsoma.lt', NULL, 'Šėtos g. 116-311', NULL, 'Kėdainiai', 'Litouwen', '95342265.0', NULL, 'LT80 7300 0101 8868 2143', NULL),
    ('Light Personeelsdiensten BV', 'particulier', NULL, 'facturen@lightpersoneelsdiensten.nl', NULL, 'Selma Lagerlöfweg 63', NULL, 'Rotterdam', 'Nederland', NULL, NULL, NULL, NULL),
    ('Van Mossel Rotterdam', 'particulier', NULL, 'simon.beumer@vanmossel.nl', NULL, 'Driemanssteeweg 690A', NULL, 'Rotterdam', 'Nederland', NULL, NULL, NULL, NULL),
    ('VALO Facilities B.V.', 'particulier', NULL, 'invoices.facilities@valo-group.eu', NULL, 'Bruistensingel 400', NULL, '''s-Hertogenbosch', 'Nederland', NULL, NULL, NULL, NULL),
    ('Lilit Home Makelaardij', 'particulier', NULL, 'info@lilithome.nl', NULL, 'Strevelsweg 72A-74A', NULL, 'Rotterdam', 'Nederland', NULL, NULL, NULL, NULL),
    ('MB Kewal', 'particulier', NULL, 'mireldak@hotmail.com', NULL, 'Sweelinckplein 15', NULL, '''s-Gravenhage', 'Nederland', NULL, NULL, 'NL83 ASNB 0932 1139 90', NULL),
    ('PRP Solutions Flex Sp. Z.O.O', 'particulier', NULL, 'costs@prpsolutions.eu', NULL, 'Dobrzynska 36', NULL, 'Plock', 'Polen', NULL, NULL, NULL, NULL),
    ('MK Contracting BV', 'particulier', NULL, 'info@mkcontracting.nl', NULL, 'Van Gijnstraat 19', NULL, 'Rijswijk ZH', 'Nederland', NULL, NULL, 'NL80 INGB 0008 5110 09', NULL),
    ('Workforce Housing Holland B.V.', 'particulier', NULL, 'invoices@w-hi.com', NULL, 'Keizersgracht 209', NULL, 'Amsterdam', 'Nederland', NULL, NULL, NULL, NULL),
    ('Fasttravel Taxi', 'particulier', NULL, 'iacovachem@gmail.com', NULL, 'Kerkweg 9A', NULL, 'Hensbroek', 'Nederland', NULL, NULL, NULL, NULL),
    ('RNVD Industries', 'particulier', NULL, 'laura.brackiene@rndv.eu', NULL, 'Taikos pr. 52C', NULL, 'Klaipeda', 'Litouwen', NULL, NULL, NULL, NULL),
    ('Flexbo B.V.', 'particulier', NULL, 'info@flexbo.nl', NULL, 'Posthoornstraat 11', NULL, 'Rotterdam', 'Nederland', NULL, NULL, 'NL34 INGB 0105 4807 97', NULL),
    ('Bw-engineering', 'particulier', NULL, 'r.adelaar@bw-engineering.nl', NULL, 'van Brakelstraat 66', NULL, 'Rotterdam', 'Nederland', NULL, NULL, 'NL74 ABNA 0554 0784 57', NULL),
    ('SHGJ Ribbink', 'particulier', NULL, 'SHGJ.Ribbink@gmail.com', NULL, 'Gagelstraat 109', NULL, 'Eindhoven', 'Nederland', NULL, NULL, NULL, NULL),
    ('Uitzendwerk B.V.', 'particulier', NULL, 'facturen@uitzendwerk.eu', NULL, 'Edisonstraat 2H', NULL, 'Emmen', 'Nederland', NULL, NULL, NULL, NULL),
    ('Showtuin Nederland B.V.', 'particulier', NULL, 'info@showtuinnederland.nl', NULL, 'Pollaan 50', NULL, 'Zutphen', 'Nederland', NULL, NULL, NULL, NULL),
    ('Buurman Vastgoed E B.V.', 'particulier', NULL, 'admin@inexho.com', NULL, 'Westerweg 291', NULL, 'Alkmaar', 'Nederland', NULL, NULL, NULL, NULL),
    ('FISSH B.V.', 'particulier', NULL, 'administratie@fissh.nl', NULL, 'Copernicusstraat 18', NULL, 'Wijchen', 'Nederland', NULL, NULL, NULL, NULL),
    ('MNA Proud Facilities B.V.', 'particulier', NULL, 'Recep@prokonak.nl', NULL, 'Tomatenlaan 29', NULL, '''s-Gravenhage', 'Nederland', NULL, NULL, 'NL59 RABO 0366 0069 59', NULL),
    ('Shtan Vitaliy', 'particulier', NULL, 'Vitalij.shtan@gmail.com', NULL, 'Trakt Lubelski 397', NULL, 'Warszawa', 'Polen', NULL, NULL, NULL, NULL),
    ('Key4work B.V.', 'particulier', NULL, 'facturen@key4work.com', NULL, 'Smaragdstraat 14', NULL, 'Hengelo OV', 'Nederland', NULL, NULL, 'NL04 INGB 0006 3999 11', NULL),
    ('CASS Construction and Steel Structures Sp. z o.o', 'particulier', NULL, 'p.samborski@cass.com.pl', NULL, 'Grzybów 78', NULL, 'Staszów', 'Polen', NULL, NULL, NULL, NULL),
    ('CB Construction UAB', 'particulier', NULL, 'info@cbconstruction.eu', NULL, 'Chemijos g.27c-62', NULL, 'Kaunas', 'Litouwen', NULL, NULL, NULL, NULL),
    ('Optima Uitzendbureau B.V.', 'particulier', NULL, 'Financieel@optimauitzendburo.nl', NULL, 'Kade 40', NULL, 'Hardinxveld Giessendam', 'Nederland', '24403530.0', NULL, NULL, NULL),
    ('Demeter BV', 'particulier', NULL, 'Factuur.demeter@knoppertamaryllis.nl', NULL, 'Madeweg 27A', NULL, 'Monster', 'Nederland', NULL, NULL, NULL, NULL),
    ('LogIQ Barendrecht B.V.', 'particulier', NULL, 'facturen0180@logiq.nl', NULL, 'Ebweg 12', NULL, 'Barendrecht', 'Nederland', NULL, NULL, NULL, NULL),
    ('Oostkracht Bemiddeling B.V.', 'particulier', NULL, 'info@ok-groep.nl', NULL, 'Zeppelinstraat 21', NULL, 'Berkel en Rodenrijs', 'Nederland', '85593087.0', NULL, NULL, NULL),
    ('Z Yilmaz', 'particulier', NULL, 'z.yilmaz@yilmazradijs.nl', NULL, 'tomatenlaan 10a', NULL, '''s-Gravenhage', 'Nederland', NULL, NULL, 'NL11 RABO 0115 2819 32', NULL),
    ('I–Housing Vastgoed Beheer B.V.', 'particulier', NULL, 'administratie@i-housingvastgoedbeheer.nl', NULL, 'Eusebiusbuitensingel 32-2', NULL, 'Arnhem', 'Nederland', '81783604.0', NULL, 'NL89 RABO 0366 5365 24', NULL),
    ('Kwekerij Stef Kleijweg', 'particulier', NULL, 'Stefkleijweg@gmail.com', NULL, 'Woudselaan 14', NULL, 'Den Hoorn ZH', 'Nederland', NULL, NULL, NULL, NULL),
    ('Duijndam Personeelsdiensten B.V.', 'particulier', NULL, 'facturen@duijndamworks.nl', NULL, 'Honderdland 241', NULL, 'Maasdijk', 'Nederland', '54370914.0', NULL, NULL, NULL),
    ('S Kleijweg', 'particulier', NULL, NULL, NULL, NULL, NULL, NULL, 'Nederland', NULL, NULL, 'NL43 RABO 0358 2186 32', NULL),
    ('Milieu Service Brabant', 'particulier', NULL, NULL, NULL, 'Schouwrooij 8', NULL, 'Boxtel', 'Nederland', '16067309.0', NULL, 'NL87 INGB 0674 7847 74', NULL),
    ('Workforce Housing International B.V', 'particulier', NULL, 'invoices@w-hi.com', NULL, 'Keizersgracht 241', NULL, 'Amsterdam', 'Nederland', NULL, NULL, 'NL37 INGB 0395 8388 94', NULL),
    ('E.C. Koornneef', 'particulier', NULL, 'info@hollandhuisvesting.nl', NULL, 'Holwerdalaan 3', NULL, 'Naaldwijk', 'Nederland', NULL, NULL, NULL, NULL),
    ('Kapitein & Personeel B.V', 'particulier', NULL, 'klaas@kapiteinpersoneel.nl', NULL, 'Marsdiep 16a', NULL, 'Urk', 'Nederland', '83620494.0', NULL, NULL, NULL),
    ('C. van Winsen', 'particulier', NULL, 'coenvanwinsen@gmail.com', NULL, 'Emmastraat 10', NULL, 'Noordwijkerhout', 'Nederland', NULL, NULL, 'NL30 RABO 0189 1515 52', NULL),
    ('Kapitan Workers Sp. Z.o.o.', 'particulier', NULL, 'kapitanworkers@outlook.com', NULL, 'Szosa Chelminska 26', NULL, 'Torun', 'Polen', NULL, NULL, NULL, NULL),
    ('Kajuit', 'particulier', NULL, 'info@kajuitbv.nl', NULL, 'Marsdiep 16a', NULL, 'Urk', 'Nederland', '85828904.0', NULL, NULL, NULL),
    ('JT Glazenwasserij en Schoonmaakdiensten', 'particulier', NULL, 'info@jtschoonmaak.nl', NULL, 'Turbinestraat 8M', NULL, 'Veenendaal', 'Nederland', '66378753.0', NULL, 'NL44 INGB 0006 8898 17', NULL),
    ('Odido Netherlands', 'particulier', NULL, NULL, NULL, 'Waldorpstraat 60', NULL, '''s-Gravenhage', 'Nederland', '33265679.0', NULL, 'NL03 COBA 0733 9597 17', NULL),
    ('R. Bassil', 'particulier', NULL, 'rogerbassil@outlook.com', NULL, 'Professor Poelslaan 58A', NULL, 'Rotterdam', 'Nederland', NULL, NULL, 'NL21 ABNA 0455 7876 62', NULL),
    ('N2people B.V.', 'particulier', NULL, 'invoice@n2people.nl', NULL, 'Mandenmakerstraat 11', NULL, 'Uden', 'Nederland', '17206030.0', NULL, NULL, NULL),
    ('P. Ter Haar-Ros', 'particulier', NULL, 'prkapper@gmail.com', NULL, 'Utrechtseweg 242', NULL, 'Amersfoort', 'Nederland', NULL, NULL, NULL, NULL),
    ('GAP Costruzioni S.r.l.', 'particulier', NULL, 'invoice@gapcostruzioni.it', NULL, 'Viale Italia 110', NULL, 'Augusta', 'Italië', NULL, NULL, 'IT29 E030 6984 6201 0000 0011 940', NULL),
    ('B. van Abeelen', 'particulier', NULL, 'vanabeelenstucadoorsbedrijf@gmail.com', NULL, 'Blauwloop 2', NULL, 'Loon op Zand', 'Nederland', NULL, NULL, 'NL95 INGB 0113 3306 85', NULL);
